######################################################################
# Automatically generated by qmake (3.0) Sat Mar 22 11:22:24 2014
######################################################################

TEMPLATE = app
TARGET = chromecast
INCLUDEPATH += .
QT += network

# Input
HEADERS += discoverer.h devicelister.h
SOURCES += discoverer.cpp main.cpp devicelister.cpp

